import {Translations} from './en';

const fr: Translations = {
  listIsEmpty: 'La liste est vide',
  no: 'Non',
  yes: 'Oui',
  cancel: 'Annuler',
  selectDate: 'Sélectionner la date',
  didRecvCode: "Vous n'avez pas reçu le code? Resend",
  contact: 'Contact',
  contactLable: 'Remplissez votre numéro de téléphone et votre emplacement',
  phoneNumber: 'Numéro de téléphone',
  state: 'État',
  Country: 'Pays',
  home: 'Accueil',
  profile: 'Profil',
  login: 'Connexion',
  logout: 'Se déconnecter',
  continuenWithFacebook: 'Continuer avec Facebook',
  continuenWithGoogle: 'Continuer avec Google',
  continuenWithApple: 'Continuer avec Apple',
  continuenWithEmail: "Continuer avec l'email",
  signUp: "S'inscrire",
  algoace: 'Algoace',
  submit: 'Soumettre',
  welcomeBack: 'Bon retour',
  selectCriteria: 'Sélectionnez vos critères',
  signInLabel: 'Remplissez votre adresse email et votre mot de passe',
  tapToProceed: 'Appuyez pour continuer',
  email: 'Email',
  forgotPasswordsmall: 'Mot de passe oublié?',
  resendCode: 'Renvoyer le code',
  password: 'Mot de passe',
  signUpLabel: 'Remplissez vos informations personnelles',
  firstName: 'Prénom',
  lastName: 'Nom de famille',
  emailAddress: 'Adresse email',
  continue: 'Continuer',
  dob: 'Date de naissance',
  forgotPasswordBold: 'Mot de passe oublié',
  forgotChangePasswordLable:
    'Mot de passe oublié, veuillez réinitialiser le mot de passe et confirmer le code via email.',
  forgotPasswordLable:
    "Nous comprenons que vous avez oublié votre mot de passe, pouvez-vous s'il vous plaît fournir votre email d'inscription",
  resetPassword: 'Réinitialiser le mot de passe',
  reEnterPassword: 'Saisissez à nouveau le nouveau mot de passe',
  confirmationCode: 'Code de confirmation',
  confirmSignUp: "Confirmer l'inscription",
  verificationSentCode: 'Le code de vérification a été envoyé à votre adresse email',
  oops: 'Oups!',
  errorBoundaryLable: "Quelque chose s'est mal passé, essayez à nouveau plus tard",
  tryAgain: 'Réessayer',
  appLabel: 'Pupspotter',
  changeLanguage: 'Changer de langue',
  MESSAGES: {
    emailRequired: "L'email est obligatoire",
    passwordRequired: 'Le mot de passe est obligatoire',
    firstNameRequired: 'Le prénom est obligatoire',
    firstNameLessLength: 'Le prénom doit comporter moins de 30 caractères',
    lastNameLessLength: 'Le nom de famille doit comporter moins de 30 caractères',
    firstNameShort: 'Prénom trop court',
    lastNameShort: 'Nom de famille trop court',
    otpLength: 'Le code OTP doit comporter exactement 6 caractères',
    otpRequired: 'Le code OTP est obligatoire',
    lastNameRequired: 'Le nom de famille est obligatoire',
    emailInvalid: "L'email est invalide",
    passwordInvalid: 'Le mot de passe est invalide',
    firstNameInvalid: 'Le prénom est invalide',
    lastNameInvalid: 'Le nom de famille est invalide',
    passwordNotMatch: 'Les mots de passe ne correspondent pas',
    passwordLength: 'Mot de passe invalide, il doit contenir une majuscule, une minuscule, une lettre et un chiffre',
  },
};

export default fr;
